from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from motor.motor_asyncio import AsyncIOMotorDatabase

from backend.api.deps import get_current_user_payload, require_doctor
from backend.api.schemas import NewsTrendPointOut, PatientOut, VitalOut
from backend.database.mongodb import get_db


router = APIRouter(dependencies=[Depends(require_doctor)])


@router.get("/patients", response_model=list[PatientOut])
async def get_assigned_patients(
    payload: dict = Depends(get_current_user_payload),
    db: AsyncIOMotorDatabase = Depends(get_db),
) -> list[PatientOut]:
    doctor_email = payload.get("sub")
    patients: list[PatientOut] = []
    async for p in db["patient"].find({"doctor_email": doctor_email}, {"_id": 0}):
        patients.append(PatientOut(**p))
    return patients


@router.get("/patient/{patient_id}/vitals", response_model=list[VitalOut])
async def get_patient_vitals(
    patient_id: str,
    payload: dict = Depends(get_current_user_payload),
    db: AsyncIOMotorDatabase = Depends(get_db),
) -> list[VitalOut]:
    doctor_email = payload.get("sub")
    patient = await db["patient"].find_one({"patient_id": patient_id}, {"_id": 0})
    if not patient:
        raise HTTPException(status_code=404, detail="Patient not found")
    if patient["doctor_email"] != doctor_email:
        raise HTTPException(status_code=403, detail="Forbidden")

    vitals: list[VitalOut] = []
    cursor = (
        db["patient_vitals"]
        .find({"patient_id": patient_id}, {"_id": 0})
        .sort("timestamp", -1)
        .limit(500)
    )
    async for v in cursor:
        vitals.append(VitalOut(**v))
    # return in chronological order
    return list(reversed(vitals))


@router.get("/patient/{patient_id}/news_trend", response_model=list[NewsTrendPointOut])
async def get_patient_news_trend(
    patient_id: str,
    payload: dict = Depends(get_current_user_payload),
    db: AsyncIOMotorDatabase = Depends(get_db),
    limit: int = 120,
) -> list[NewsTrendPointOut]:
    """
    Return precomputed NEWS2/adjusted score trend points for the patient.
    These points are generated by the monitoring service.
    """
    doctor_email = payload.get("sub")
    patient = await db["patient"].find_one({"patient_id": patient_id}, {"_id": 0})
    if not patient:
        raise HTTPException(status_code=404, detail="Patient not found")
    if patient["doctor_email"] != doctor_email:
        raise HTTPException(status_code=403, detail="Forbidden")

    limit = max(1, min(limit, 500))
    points: list[NewsTrendPointOut] = []
    cursor = (
        db["patient_news_trend"]
        .find({"patient_id": patient_id}, {"_id": 0})
        .sort("timestamp", -1)
        .limit(limit)
    )
    async for p in cursor:
        points.append(NewsTrendPointOut(**p))
    return list(reversed(points))

